---
- name: get registry config
  hosts: k8s_cluster
  become: true
  gather_facts: false
  vars: 
    containerd_cfg_dir: /etc/containerd
    # server: https://core.harbor.k8s.ebupt.com
  tasks:
    - name: Extract the path after ://
      set_fact:
        registry_host: "{{ server | regex_replace('^[^:/]+://', '') }}"

    - name: Remove specified directory from containerd_cfg_dir
      file:
        path: "{{ containerd_cfg_dir }}/certs.d/{{ registry_host }}"
        state: absent

    - name: Restart containerd service
      systemd:
        name: containerd
        state: restarted

    - name: delete /etc/hosts entry
      ansible.builtin.lineinfile:
        path: /etc/hosts  
        regexp: '^.*{{ registry_host }}.*$'
        state: absent