name: Auto Merge Approved PR

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  check_suite:
    types: [completed]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    # 仅当 PR 处于 open 状态时触发
    if: github.event.pull_request.state == 'open'

    steps:
      # 步骤 1：更新 PR 分支（可选，解决冲突）
      - name: Update PR Branch
        uses: adRise/update-pr-branch@v0.9.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: auto-update branch"

      # 步骤 2：自动合并操作
      - name: Auto Merge PR
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # 合并条件配置
          condition: "check-success && approved && label!='do-not-merge'"
          # 合并方法（merge/squash/rebase）
          method: "merge"
          # 冲突自动解决策略（可选）
          conflict-resolution: "rebase"