name: Auto-Merge Approved PR

on:
  pull_request:
    types: [opened, reopened, synchronize]
  check_suite:
    types: [completed]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    # 仅在PR处于开放状态时执行
    if: github.event.pull_request.state == 'open'
    
    steps:
      # 步骤1：检出代码（非必需，但保持上下文）
      - name: Checkout
        uses: actions/checkout@v4

      # 步骤2：自动合并操作
      - name: Merge PR
        uses: actions/github-script@v6
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: process.env.PR_NUMBER
            });

            // 检查条件：所有状态检查通过 + 无冲突 + 可合并
            if (pr.mergeable && pr.mergeable_state === 'clean') {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: process.env.PR_NUMBER,
                merge_method: 'merge'  # 可选 squash/rebase
              });
              console.log('PR merged successfully');
            } else {
              console.log('PR not ready for merging');
            }
          # 使用更高权限的Token
          github-token: ${{ secrets.ACTION_WXL }}